db = "/app/strfry-db/"

dbParams {
    maxreaders = 256
    mapsize = 10995116277760
    noReadAhead = false
}

events {
    maxEventSize = 65536
    rejectEventsNewerThanSeconds = 900
    rejectEventsOlderThanSeconds = 94608000
    rejectEphemeralEventsOlderThanSeconds = 60
    ephemeralEventsLifetimeSeconds = 300
    maxNumTags = 2000
    maxTagValSize = 1024
}

relay {
    bind = "0.0.0.0"
    port = 7777
    nofiles = 524288
    realIpHeader = "x-forwarded-for"

    auth {
        enabled = false
        serviceUrl = ""
    }

    info {
        name = "Wired Admin"
        description = "A Wired proof-of-work Nostr relay backed by strfry."
        pubkey = ""
        self = ""
        contact = ""
        icon = "https://raw.githubusercontent.com/smolgrrr/wired-admin/main/smolgrrr-wired-admin/icon.png"
        banner = ""
        privacy = ""
        terms = ""
        nips = ""
    }

    maxWebsocketPayloadSize = 131072
    maxReqFilterSize = 200
    autoPingSeconds = 55
    enableTcpKeepalive = true
    queryTimesliceBudgetMicroseconds = 10000
    maxFilterLimit = 500
    maxTagsPerFilter = 3
    maxFilterLimitCount = 1000000
    maxSubsPerConnection = 200
    maxPendingOutboundBytes = 33554432

    writePolicy {
        plugin = ""
        timeoutSeconds = 10
    }

    compression {
        enabled = true
        slidingWindow = true
    }

    logging {
        dumpInAll = false
        dumpInEvents = false
        dumpInReqs = false
        dbScanPerf = false
        invalidEvents = true
    }

    numThreads {
        ingester = 3
        reqWorker = 3
        reqMonitor = 3
        negentropy = 2
    }

    negentropy {
        enabled = true
        maxSyncEvents = 1000000
    }

    filterValidation {
        enabled = false
        maxFiltersPerReq = 3
        minFiltersPerReq = 1
        maxKindsPerFilter = 3
        allowedKinds = ""
        requireAuthorOrTag = false
    }
}
